services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${DB_USER-user}
      - POSTGRES_PASSWORD=${DB_PASSWORD-password}
      - POSTGRES_DB=${DB_NAME-meal_planner}
    ports:
      - "${DB_PORT-5432}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  # The application service is commented out for now.
  # It will be used later to build and run the FastAPI application.
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/meal_planner_db
