services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meal_planner_db
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/

  # The application service is commented out for now.
  # It will be used later to build and run the FastAPI application.
  # app:
  #   build: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   environment:
  #     - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/meal_planner_db
